export const PRODUCTS = [
  {
    id: '1',
    title: 'product 1',
    description: 'description of product 1',
    price: 42,
    count: 42,
  },
  {
    id: '2',
    title: 'product 2',
    description: 'description of product 2',
    price: 41,
    count: 42,
  },
  {
    id: '3',
    title: 'product 3',
    description: 'description of product 3',
    price: 40,
    count: 42,
  },
  {
    id: '4',
    title: 'product 4',
    description: 'description of product 4',
    price: 39,
    count: 42,
  },
  {
    id: '5',
    title: 'product 5',
    description: 'description of product 5',
    price: 38,
    count: 42,
  },
  {
    id: '6',
    title: 'product 6',
    description: 'description of product 6',
    price: 37,
    count: 42,
  },
  {
    id: '7',
    title: 'product 7',
    description: 'description of product 7',
    price: 36,
    count: 42,
  },
  {
    id: '8',
    title: 'product 8',
    description: 'description of product 8',
    price: 35,
    count: 42,
  },
  {
    id: '9',
    title: 'product 9',
    description: 'description of product 9',
    price: 34,
    count: 42,
  },
  {
    id: '10',
    title: 'product 10',
    description: 'description of product 10',
    price: 37,
    count: 42,
  },
] as const;
